---
title: "Analiza pokrycia"
author: "A.Brodecka"
date: "29 kwietnia 2017"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include= FALSE}
setwd('/media/ola/EEAABE9FAABE642D/metylacja')
source('/media/ola/EEAABE9FAABE642D/metylacja/metr/Rcodes/function_preprocessing.R')
source('/media/ola/EEAABE9FAABE642D/metylacja/metr/Rcodes/libraries.R')

data <- readRDS('dane/to_analysis.rds')

options(scipen=10000)

```

## Podzia³ po gapach

```{r}

create_tiles(data, 20) %>% group_by(tiles) %>% summarize(n = n()/2) -> d20
ggplot(d20, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 30) + ggtitle('Podzial do 20')


create_tiles(data, 50) %>% group_by(tiles) %>% summarize(n = n()/2) -> d50
ggplot(d50, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 50)+ ggtitle('Podzial do 50')

create_tiles(data, 100) %>% group_by(tiles) %>% summarize(n = n()/2) -> d100
ggplot(d100, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 60)+ ggtitle('Podzial do 100')

create_tiles(data, 150) %>% group_by(tiles) %>% summarize(n = n()/2) -> d150
ggplot(d150, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 60)+ ggtitle('Podzial do 150')

create_tiles(data, 200) %>% group_by(tiles) %>% summarize(n = n()/2) -> d200
ggplot(d200, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 70)+ ggtitle('Podzial do 200')

create_tiles(data, 300) %>% group_by(tiles) %>% summarize(n = n()/2) -> d300
ggplot(d300, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 70)+ ggtitle('Podzial do 300')

create_tiles(data, 400) %>% group_by(tiles) %>% summarize(n = n()/2) -> d400
ggplot(d400, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 80)+ ggtitle('Podzial do 400')

create_tiles(data, 500) %>% group_by(tiles) %>% summarize(n = n()/2) -> d500
ggplot(d500, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 80)+ ggtitle('Podzial do 500')

```


## Podzia³ na regiony o d³ugoœci 1000


```{r}
data$tiles = data$poz %/% 1000
data$tiles <- as.factor(data$tiles)
data %>% group_by(tiles, chr) %>% summarize(n = n()/2) -> tiles1000 
ggplot(tiles1000 , aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 80)+ ggtitle('Podzial 1000tiles')



data$tiles = data$poz %/% 500
data$tiles <- as.factor(data$tiles)
data %>% group_by(tiles, chr) %>% summarize(n = n()/2) -> tiles500
ggplot(tiles500, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 80)+ ggtitle('Podzial 500tiles')


data$tiles = data$poz %/% 2000
data$tiles <- as.factor(data$tiles)
data %>% group_by(tiles, chr) %>% summarize(n = n()/2) -> tiles2000
ggplot(tiles2000, aes(n)) + geom_histogram(binwidth = 1) + xlim(0, 80)+ ggtitle('Podzial 2000tiles')


```

