---
title: "Regresja kwantylowa"
author: "A.Brodecka"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r include= FALSE}
source('/media/ola/EEAABE9FAABE642D/metylacja/metR/Rcodes/function_preprocessing.R')
source('/media/ola/EEAABE9FAABE642D/metylacja/metR/Rcodes/libraries.R')

```

# Regresja dla kolejnych decyli:

```{r}
setwd('/media/ola/EEAABE9FAABE642D/metylacja')
n_sqrt3 <- (1:80)^(-1/3)


q <- seq(0.1,0.9, by = 0.1)
data <- list()
get_data <- function(d){
  d$coefficients[2,1]*n_sqrt3 + d$coefficients[1,1]
}


for(i in 1:length(q)){
  data_temp <- readRDS(paste0('p1_', q[i], '.rds'))
  data[[i]] <- data.frame(result = get_data(data_temp), type = q[i], n = 1:80)
  }

data <- do.call('rbind', data)

ggplot(data, aes(y = result, group = type, x = n, colour = as.factor(type))) + geom_line() +
  ggtitle('Regresja z decylami')

```

# Przybli¿enia regresji ró¿nymi metodami

```{r}

function_list <- list()

for (i in 1:80){
  data_temp <- data %>% filter(n == i)
  function_list[[i]] <- splinefun(y = data_temp$type, x = data_temp$result)  
}


col <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", 
         "#CC79A7", "#CC6666", "#9999CC", "#66CC99", '#FFCC00')


ggplot(data.frame(x = c(0,1)), aes(x))  + ggtitle('Spline perdiodic') + xlim(0,0.18) +
  stat_function(fun = function_list[[5]], aes(colour = '5')) +
  stat_function(fun = function_list[[10]], aes(colour = '10')) +
  stat_function(fun = function_list[[15]], aes(colour = '15')) +
  stat_function(fun = function_list[[20]], aes(colour = '20')) +
  stat_function(fun = function_list[[25]], aes(colour = '25')) +
  stat_function(fun = function_list[[30]], aes(colour = '30')) +
  stat_function(fun = function_list[[35]], aes(colour = '35')) +
  stat_function(fun = function_list[[40]], aes(colour = '40')) +
  stat_function(fun = function_list[[45]], aes(colour = '45')) +
  stat_function(fun = function_list[[50]], aes(colour = '50')) +
  stat_function(fun = function_list[[55]], aes(colour = '55')) +
  stat_function(fun = function_list[[60]], aes(colour = '60')) +
  scale_colour_manual("N", values = col)
  
  

function_list2 <- list()

for (i in 1:80){
  data_temp <- data %>% filter(n == i)
  function_list2[[i]] <- approxfun(y = data_temp$type, x = data_temp$result)  
}


col <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", 
         "#CC79A7", "#CC6666", "#9999CC", "#66CC99", '#FFCC00')


ggplot(data.frame(x = c(0,1)), aes(x))  + ggtitle('Aproksymacja liniowa') + xlim(0,0.18) +
  stat_function(fun = function_list2[[5]], aes(colour = '5')) +
  stat_function(fun = function_list2[[10]], aes(colour = '10')) +
  stat_function(fun = function_list2[[15]], aes(colour = '15')) +
  stat_function(fun = function_list2[[20]], aes(colour = '20')) +
  stat_function(fun = function_list2[[25]], aes(colour = '25')) +
  stat_function(fun = function_list2[[30]], aes(colour = '30')) +
  stat_function(fun = function_list2[[35]], aes(colour = '35')) +
  stat_function(fun = function_list2[[40]], aes(colour = '40')) +
  stat_function(fun = function_list2[[45]], aes(colour = '45')) +
  stat_function(fun = function_list2[[50]], aes(colour = '50')) +
  stat_function(fun = function_list2[[55]], aes(colour = '55')) +
  stat_function(fun = function_list2[[60]], aes(colour = '60')) +
  scale_colour_manual("N", values = col)



function_list3 <- list()

for (i in 1:80){
  data_temp <- data %>% filter(n == i)
  function_list3[[i]] <- splinefun(y = data_temp$type, x = data_temp$result, method = 'natural')  
}


ggplot(data.frame(x = c(0,1)), aes(x))  + ggtitle('Spline natural') + xlim(0,0.18) +
  stat_function(fun = function_list3[[5]], aes(colour = '5')) +
  stat_function(fun = function_list3[[10]], aes(colour = '10')) +
  stat_function(fun = function_list3[[15]], aes(colour = '15')) +
  stat_function(fun = function_list3[[20]], aes(colour = '20')) +
  stat_function(fun = function_list3[[25]], aes(colour = '25')) +
  stat_function(fun = function_list3[[30]], aes(colour = '30')) +
  stat_function(fun = function_list3[[35]], aes(colour = '35')) +
  stat_function(fun = function_list3[[40]], aes(colour = '40')) +
  stat_function(fun = function_list3[[45]], aes(colour = '45')) +
  stat_function(fun = function_list3[[50]], aes(colour = '50')) +
  stat_function(fun = function_list3[[55]], aes(colour = '55')) +
  stat_function(fun = function_list3[[60]], aes(colour = '60')) +
  scale_colour_manual("N", values = col)


function_list4 <- list()

for (i in 1:80){
  data_temp <- data %>% filter(n == i)
  function_list4[[i]] <- splinefun(y = data_temp$type, x = data_temp$result, method = 'fmm')  
}


ggplot(data.frame(x = c(0,1)), aes(x))  + ggtitle('Spline fmm') + xlim(0,0.18) +
  stat_function(fun = function_list4[[5]], aes(colour = '5')) +
  stat_function(fun = function_list4[[10]], aes(colour = '10')) +
  stat_function(fun = function_list4[[15]], aes(colour = '15')) +
  stat_function(fun = function_list4[[20]], aes(colour = '20')) +
  stat_function(fun = function_list4[[25]], aes(colour = '25')) +
  stat_function(fun = function_list4[[30]], aes(colour = '30')) +
  stat_function(fun = function_list4[[35]], aes(colour = '35')) +
  stat_function(fun = function_list4[[40]], aes(colour = '40')) +
  stat_function(fun = function_list4[[45]], aes(colour = '45')) +
  stat_function(fun = function_list4[[50]], aes(colour = '50')) +
  stat_function(fun = function_list4[[55]], aes(colour = '55')) +
  stat_function(fun = function_list4[[60]], aes(colour = '60')) +
  scale_colour_manual("N", values = col)


```

